# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category')),
            ],
        ),
    ]
