# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='link',
        ),
    ]
