# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_movie_file_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
