# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170425_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(max_length=300, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='images'),
        ),
    ]
