# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170425_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
