# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170425_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
