# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_category_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='/mnt/FlashDrive/wifi_storage/movies/'),
        ),
    ]
